### PR TITLE
fix(gmap-vue): fix ref conflict on autocomplete component

### PR DESCRIPTION
**Pull request by farooqaaa**
This issue had me pulling my hair for an hour. After checking my code for the hundredth time, I decided to look into the code of this package to see if the issue was there.

### The Issue
**This only occurs when you create a `gmap-autocomplete` component with another component in its slot.**

If you create only one `gmap-autocomplete` component, it works fine but if there's more than one; only the last one will work.  Not only that, if you have another component or element somewhere in the context with the `ref` "input", it will ignore the slot and apply autocomplete to that.

### What's causing it
At line 50, there's `this.$scopedSlots.input()[0].context.$refs.input`. As it's accessing the context of the slotted component (which is the context of its parent component), `$refs.input` can refer to anything in that context with the same ref. Here's an example:

Here only the second component will work:

```
<gmap-autocomplete>
  <template ...>
    <my-component ref="input" />
   </template>
</gmap-autocomplete>

<gmap-autocomplete>
  <template ...>
    <my-component ref="input" />
   </template>
</gmap-autocomplete>
````

And here the `<input />` outside `gmap-autocomplete` will get autocomplete:

```
<gmap-autocomplete>
  <template ...>
    <my-component ref="input" />
   </template>
</gmap-autocomplete>

<input ref="input" />
````

### The Fix
I have added a new prop `slotRefName` which can be used to specify the unique ref of the slot if there's more than one instance of `gmap-autocomplete` or to avoid conflict with other elements. 

You can now do this if you have multiple instances:

```
<gmap-autocomplete slot-ref-name="address1">
  <template ...>
    <my-component ref="address1" />
   </template>
</gmap-autocomplete>

<gmap-autocomplete slot-ref-name="address2">
  <template ...>
    <my-component ref="address2" />
   </template>
</gmap-autocomplete>
```

### CODE REVIEW

**Comment by JBtje** [comment]
@diegoazh When is this pull request going to be accepted?
It is simple, doesn't break anything and solved the problem that you cannot use 2 custom elements with gmaps-autocomplete on the same page...

I implemented the code locally, and can confirm it's working w/o problems!

**Comment by diegoazh** [comment]
Hi @JBtje sorry, I'm very busy these days. This is not merged yet for many reasons, the first one is because I not reviewed yet but the other reasons are because you don't follow our style guide. The name of the PR is not in the correct form, your commits follow the semantic commits doesn't follow our style guide too. Please read it, fix it and when all validations are ready I will review it.
Thanks for your contribution and I hope your changes soon 👍🏽

**Comment by diegoazh** [comment]
@JBtje I reviewed your changes and you duplicated the solution because their is a `childRefName` prop that helps you with what you try to do

```vue
<gmap-autocomplete child-ref-name="address1">
  <template ...>
    <my-component ref="address1" />
   </template>
</gmap-autocomplete>

<gmap-autocomplete child-ref-name="address2">
  <template ...>
    <my-component ref="address2" />
   </template>
</gmap-autocomplete>
```

Sorry for waist your time, the documentation is not clear at all and I am working on it to improve the legibility of the API and its documentation.

On the other hand, there is an error con the code if you found it and you follow our contribution guide I will accept your PR, otherwise, I will land a fix at the end of the day.

**Comment by JBtje** [comment]
> @JBtje I reviewed your changes and you duplicated the solution because their is a `childRefName` prop that helps you with what you try to do

Hi @diegoazh, this eeh.... isn't my pull request... its by @farooqaaa

> ```
> <gmap-autocomplete child-ref-name="address1">
>   <template ...>
>     <my-component ref="address1" />
>    </template>
> </gmap-autocomplete>
> 
> <gmap-autocomplete child-ref-name="address2">
>   <template ...>
>     <my-component ref="address2" />
>    </template>
> </gmap-autocomplete>
> ```
> 
> Sorry for waist your time, the documentation is not clear at all and I am working on it to improve the legibility of the API and its documentation.
> 
> On the other hand, there is an error con the code if you found it and you follow our contribution guide I will accept your PR, otherwise, I will land a fix at the end of the day.


Within my `<template ...>` I'm using an element-ui component. However, with `child-ref-name`, it's not working (spend too much time on that...). I implemented this pull request, and it worked directly, so, that's why i did the request for when it would be implemented.

**Comment by diegoazh** [comment]
@JBtje 🤦‍♂️ yes I made a mistake sorry, I reviewed the code on a branch where I made changes instead of master. Sorry about that.
Please fix your commits to pass all required validations.

**Comment by diegoazh** [comment]
@ @JBtje > > @JBtje I reviewed your changes and you duplicated the solution because their is a `childRefName` prop that helps you with what you try to do
> 
> Hi @diegoazh, this eeh.... isn't my pull request... its by @farooqaaa
> 
> > ```
> > <gmap-autocomplete child-ref-name="address1">
> >   <template ...>
> >     <my-component ref="address1" />
> >    </template>
> > </gmap-autocomplete>
> > 
> > <gmap-autocomplete child-ref-name="address2">
> >   <template ...>
> >     <my-component ref="address2" />
> >    </template>
> > </gmap-autocomplete>
> > ```
> > 
> > 
> > Sorry for waist your time, the documentation is not clear at all and I am working on it to improve the legibility of the API and its documentation.
> > On the other hand, there is an error con the code if you found it and you follow our contribution guide I will accept your PR, otherwise, I will land a fix at the end of the day.
> 
> Within my `<template ...>` I'm using an element-ui component. However, with `child-ref-name`, it's not working (spend too much time on that...). I implemented this pull request, and it worked directly, so, that's why i did the request for when it would be implemented.

oh sorry @JBtje another mistake 🤦‍♂️, @farooqaaa can you make the required changes?

**Review by diegoazh — APPROVED** [review]

**Comment by diegoazh** [comment]
Ok how this is a mistake and I made mistakes reviewing this. I will make an exception and merge this PR. Thank you @farooqaaa for fixing this bug.

**Comment by farooqaaa** [comment]
No worries @diegoazh. Thanks for merging it.

**Comment by JBtje** [comment]
@diegoazh awesome! thanks for the great package!

**Pull request merged**
